blog/urls.py
from django.urls import path
from .views import render_posts, post_detail
app_name ="blog"
urlpatterns = [

    path("", render_posts, name='posts'),
    path("<int:post_id>", post_detail,name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

from blog import urls

from portfolio import views
urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))

]

urlpatterns += static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
class Post(models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models

from django.db.models.fields import CharField, URLField

from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)

    description = CharField(max_length=250)

    image = ImageField(upload_to='portfolio/images')

    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    articulos = Post.objects.all()
    return render(request,'posts.html',
                  {'posts':articulos})
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render

from .models import Project

# Create your views here.​

def home(request):
    projects = Project.objects.all()

    return render(request,'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content%}
<h1>"proyecto"</h1>
<h2>{{post.title}}</h2>
<h3>{{post.date}}</h3>
<p>{{post.description|safe}}</p>
<img src="{{post.image.url}}" alt="{{post.title}}" width="300" height="250"     >

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content%}
<h1>Posts</h1>
{% for post in posts %}
    <h2>{{post.title}}</h2>
    <p>{{post.description|safe|truncatechars:100}}</p>
    <p>{{post.date|date:'M d Y'|upper}}</p>
    <img src="{{post.image.url}}" alt="{{post.title}}" width="600" height="450"
    <br>
{% endfor %}
{% endblock %}

portfolio/templates/home.html
={% extends 'layout.html' %}
{% block content%}
{% load static%}
<header class="row bg-white ">
    <div class="col-md-4">

    </div> 
    <div class="col-md-8 my-auto ">
    <h1><strong>Paul cruz</strong></h1>
    <h3> Soy un estudiante de la ULEAM , fanaticos de los carros </h3>
    <p style="text-align : justify;"></p>
    <a href="{% static 'curriculum.pdf'%}"class="btn btn-primary btn-lg rounded-0 my-3">Descarga aquí</a>

    <div class="col-md-7">
    <text-align"left"><img src="{% static 'bg.jpg'%}" alt="" width="350" height="350"> 
    </div>
</div>

</header>

<div class="row my-4 text-center">
<h3> MIS PROYECTOS</h3>
<p>mis pequeños proyectos.</p>

    {% for project in projects %}

<div class="col-md-4 p-4" >
    <div class="card bg-white card-project">
        <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>
                <img src="{{project.image.url}}" alt="{{project.title}}"class="card-img-top" >

                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
            {% endif %}
        </div>
    </div>

</div>



{%endfor %}
{% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible"content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>documento</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    {%include 'partials/navbar.html'%}
    {% block content %}

    {% endblock %}
    <div class="container p-4"></div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-black">
    <div class="container-fluid">
      <img src="{% static 'perfil.jpg'%}" alt="" width="100" height="100">
      <a class="navbar-brand fw-bold fst-italic" href="/">Paul Cruz</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link "   href="{% url 'blog:posts' %}">blog</a>
          </li>
          <li class=""nav-item d-flex align-items-center"">
            <a class="btn btn-primary btn-sm" href="{% static 'curriculum.pdf' %}" target="_blank">Descargalo</a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item">
          </li>
        </ul>
      </div>
    </div>
  </nav>